language: node_js
node_js:
- "8"

services:
- docker

dist: trusty

before_install: |
    set -ev
    set -o pipefail
    npm install -g @alrra/travis-scripts

env:
    global:
    - secure: "p+qn6YW8myj1mH9edoNfNCf7gQmsKeK5yy6BXarjaEUuuoH2OtXq1+GKQZFM4V60hxvy/4ab0+r8OPlhIJqiKe9/k6XkJTtjWBPIIYT6KuS1psFHAqWGaWE5vxJ7yRGivw4AhEiXl8gTYJkB2+WktuMNdvVfEINLXDJHEHh+EJV25q2ZtfajcFXPqQJXt1EFICeWT1yYeLo1R09kZvulfWc/i4F8T+oCCHUqa0NVn38kLbh6jPPgZAe91W9zRKiEhFPbCOvQuJcIDelJbqjpzeWCirJzBf9jqSz9DlEmKflnPTZ7FW3Kz4QtPZvtXgRjboiYBzhYxNSvxoGyMFdUuuvDZI+732B9T+bl6SyZXmG/xUJgYyLxx/YFQZ+ATpB2SK8URiftmBuRAeF5LDuJmfBEmjV0mcgepoVG5rwOFMcErHpr5+JVZkqdjImZo5/D8XS8+yMl2qtv0cBpPUtXaNKJHV/yHvP2RRTJqncSP3UPQFQX7TzQwEiYCfdwx9ZA7JsYaIDOZwj4OFgSl6QE2QFgsIK6us73mQgo+gtaw1X87GInuJYRl8UoG1+OSVUof4pMDKX3FVkonuEJQdrFFd60SRv2kktlAXwvYnKSiBUtRCZZaFJHjogYzAFhsJ/CCcmzMnMxl98E6VuQzx0If3qaZ8mxLLITi8n0ca9gJcM="
    - secure: "KCsIcbtShjcZTa+MFzbULdp5npWCi6MuTYPIaGHOhdGlNINa3wuzUai1DvROKx3758wlMzGg4YGKRwVNRLpE+d0oZqThiBW6LWGmZskDcqdB4a0/+Ft9fSyO3a93rH8ieoINrbHM2fg9QB+ldsAHI/9gxtPQ44KblB5swKYqQTGRzVPtNgrLkaR5pYnWUE26C8pa3K8SKjw3gxK3E9JC5fmoMiEzOZqlT6LvWARFcZS4ETlwo2SDJAUoV5y8wRJrTCb6n7hXnR4AjloqGkHkOIvLL0XcRjAvzD++BzTVcFzUr9WMDnIomQXzvqJ0CxcvnGrNt81dVBEfNCBjHQQvarnlfjBdEj+aNtGLdDTo6tIQkRsWpnIrjyoJpsQqGuS/NIhhoBjZbqIREGA41BoQnOMNJ63xvOJ7w0l3JpoaBVTRd1qooz9VwWDGdp0bGc/Nvk8+jQKGr+m4HdALZx278bxsAVAOghgSJ5QnpF+KdKzisAPvEqwx6bZx+g7gdEuK81mDV92pu8SNGbLA+DHGVweo0STli5ykZNzCso9Lz6fp418/93Go4byPaIhZ1scrDmJkB5awtvNjUv368ZfeuzuSH7SqLjPYlw7Cq/BxKa80nAYiVLTUPQZyy/8FaVqmxOKEF9dQMH0zMnGFuw9vGleyVtfDAVk961rGYWCXDRI="

# NOTE: the unit test and integration test jobs are only run "for the PR". In this case the encrypted env vars are not present (are blank).
# The NPM and Docker Hub publish jobs are only run when the PR is merged. In this case the encrypted env vars are present, since the repo slug is hyperledger/caliper.
# So the presence of encrypted vars are used as conditions for the jobs.
jobs:
    include:
    - stage: checks and unit tests
      name: Show various information about the CI build
      script: ./.travis/build-info.sh
    - if: env(NPM_TOKEN) IS blank
      name: Package name check, license check, lint check, unit tests
      script: ./.travis/checks-and-unit-tests.sh

    # parallel integrations tests
    - stage: benchmark integration tests
      if: env(NPM_TOKEN) IS blank
      name: HL Fabric integration test
      script: BENCHMARK=fabric ./.travis/benchmark-integration-test-direct.sh
    - name: Ethereum integration test
      script: BENCHMARK=ethereum ./.travis/benchmark-integration-test-direct.sh
    - name: HL Sawtooth integration test
      script: BENCHMARK=sawtooth ./.travis/benchmark-integration-test-direct.sh
    - name: HL Besu integration test
      script: BENCHMARK=besu ./.travis/benchmark-integration-test-direct.sh
    - name: FISCO-BCOS integration test
      script: BENCHMARK=fisco-bcos ./.travis/benchmark-integration-test-direct.sh
    - name: Generator integration test
      script: BENCHMARK=generator ./.travis/benchmark-integration-test-direct.sh

    # publish npm packages
    - stage: npm publish
      name: Publishing to NPM
      if: env(NPM_TOKEN) IS present
      script: ./.travis/npm-publish.sh

      # publish docker image
    - stage: docker publish
      name: Publishing to Docker Hub
      if: env(DOCKER_TOKEN) IS present
      script: ./.travis/docker-publish.sh

cache:
  directories:
    - node_modules
sudo: required
notifications:
  webhooks:
    on_success: always # default: always
    on_failure: always # default: always
    on_start: always   # default: never
    on_cancel: always # default: always
    on_error: always # default: always
